# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='line_id',
            new_name='lineid',
        ),
    ]
